### ISSUE TITLE
向目标wss发送连接一直无法成功连接

### ISSUE THREAD

**Issue by Gavin-Zhang-Code** [YunzhiYike/douyin-live#18]
我使用您写的wss地址，然后再ping中发送链接请求一直显示申请连接中，然后我使用我的web端访问拿到wss地址后，然后将ping中的数据包改成我这边捕获的显示 bad request，想问一下这是为什么呀

**Comment by Gavin-Zhang-Code** [comment]
![1688433674130](https://github.com/YunzhiYike/douyin-live/assets/54618823/cd0df933-8871-47b1-b18d-0194a3458843)
这个是根据您的运行，一直在ping，发送请求。然后我又根据自己访问的wss和它发送的数据包更改了您写的wssserverstart和ping，换成了我的wss链接和建立连接的数据包，但是也是一直显示建立连接中
![image](https://github.com/YunzhiYike/douyin-live/assets/54618823/17de3537-f8fc-4a55-b074-d9b550581782)

**Comment by YunzhiYike** [comment]
你这个ws地址是直接从抖音直播平台提取的还是
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 09:26 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |


这个是根据您的运行，一直在ping，发送请求。然后我又根据自己访问的wss和它发送的数据包更改了您写的wssserverstart和ping，换成了我的wss链接和建立连接的数据包，但是也是一直显示建立连接中

**Comment by Gavin-Zhang-Code** [comment]
我开始以为建立链接的数据包是不是写错了，我分别试了hb  :hb  :.hb  : hb 这四种还是都在ping，没有接收到返回的消息

**Comment by Gavin-Zhang-Code** [comment]
我这个是从前端访问目标地址的时候，抓的websocket地址

**Comment by Gavin-Zhang-Code** [comment]
![image](https://github.com/YunzhiYike/douyin-live/assets/54618823/c7478966-aa29-4c83-8df4-c79149b18588)
用的这个wss，然后按照您的写法，更改了roomid和wsspushroomid

**Comment by YunzhiYike** [comment]
对啊，心跳包都是小问题，主要是首次连接成功后只要直播间不关就会主动推数据；但是这是建立在正常按抖音ws授权连接的流程可以
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 09:28 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |

我开始以为建立链接的数据包是不是写错了，我分别试了hb :hb :.hb : hb 这四种还是都在ping，没有接收到返回的消息

**Comment by YunzhiYike** [comment]
不行，缺少校验参数
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 09:29 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |


用的这个wss，然后按照您的写法，更改了roomid和wsspushroomid

**Comment by YunzhiYike** [comment]
不能直接用抓出来的wss地址
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 09:28 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |

我这个是从前端访问目标地址的时候，抓的websocket地址

**Comment by Gavin-Zhang-Code** [comment]
哦哦，因为最开始用您的那个访问流程，一直卡在心跳包上，是不是主机服务器接受的消息不对还是我们的header有问题呢，一直不给咱们返回消息，无法建立连接

**Comment by YunzhiYike** [comment]
Header
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 09:32 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |

哦哦，因为最开始用您的那个访问流程，一直卡在心跳包上，是不是主机服务器接受的消息不对还是我们的header有问题呢，一直不给咱们返回消息，无法建立连接

**Comment by Gavin-Zhang-Code** [comment]
好的，我再去调一下header看一下，谢谢啦

**Comment by Gavin-Zhang-Code** [comment]
您好，您那边可以连接嘛，可以给我看一下您写的嘛，我改了header然后也试了在wss链接中根据每次请求加入user_unique_id，还是无法建立正确的连接
![image](https://github.com/YunzhiYike/douyin-live/assets/54618823/1f472352-417e-4dc7-a06a-7c98bdc24118)

**Comment by YunzhiYike** [comment]
不是已经开源了吗
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 13:51 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |

您好，您那边可以连接嘛，可以给我看一下您写的嘛，我改了header然后也试了在wss链接中根据每次请求加入user_unique_id，还是无法建立正确的连接

**Comment by Gavin-Zhang-Code** [comment]
嗯嗯，就是现在貌似无法链接，就是想问您一下您现在可以链接吗，因为现在一直卡在发送心跳包这里，无法获取服务器的响应，所以想问您一下，您这边现在可以吗，是不是他们的wss更新了还是什么原因呢

**Comment by YunzhiYike** [comment]
你直接拉我们开源的代码跑就好了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 14:06 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |

嗯嗯，就是现在貌似无法链接，就是想问您一下您现在可以链接吗，因为现在一直卡在发送心跳包这里，无法获取服务器的响应，所以想问您一下，您这边现在可以吗，是不是他们的wss更新了还是什么原因呢

**Comment by YunzhiYike** [comment]
开源的代码都是正常可运行的
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 14:06 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |

嗯嗯，就是现在貌似无法链接，就是想问您一下您现在可以链接吗，因为现在一直卡在发送心跳包这里，无法获取服务器的响应，所以想问您一下，您这边现在可以吗，是不是他们的wss更新了还是什么原因呢

**Comment by Gavin-Zhang-Code** [comment]
不好意思哥，我找到问题了，他建立了链接，但是我没有初始化logging导致的没有显示出来，感谢感谢

**Comment by Gavin-Zhang-Code** [comment]
兄弟，你知道怎么把uid转成sec_uid嘛或者uid跳转到个人主页

**Comment by YunzhiYike** [comment]
没用到所以没研究过
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月04日 16:43 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 向目标wss发送连接一直无法成功连接 (Issue #18) |

兄弟，你知道怎么把uid转成sec_uid嘛或者uid跳转到个人主页
