### ISSUE TITLE
匿名直播间消息

### ISSUE THREAD

**Issue by Gavin-Zhang-Code** [YunzhiYike/douyin-live#19]
您好，想请教一下，如果想爬取匿名直播间的消息的话，能爬取到userid吗

**Comment by YunzhiYike** [comment]
匿名都不行的
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月05日 21:44 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [YunzhiYike/douyin-live] 匿名直播间消息 (Issue #19) |

您好，想请教一下，如果想爬取匿名直播间的消息的话，能爬取到userid吗
