### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by NXueqi** [YunzhiYike/douyin-live#2]
出这个error是怎么回事呀？
error ("hostname 'webcast3-ws-web-lf.douyin.com' doesn't match either of '*.alicdn.com', '*.cmos.greencompute.org', 'cmos.greencompute.org', 'm.intl.taobao.com', '*.mobgslb.tbcache.com', 'alikunlun.com', '*.alikunlun.com', 's.tbcdn.cn', '*.django.t.taobao.com', 'alicdn.com'",)

**Comment by YunzhiYike** [comment]
是你的websocket扩展安装的不对

**Comment by YunzhiYike** [comment]
pip install websocket-client 用这个试试

**Comment by YunzhiYike** [comment]
如果不行就用这个pip install websockets

**Comment by NXueqi** [comment]
好了好了，跪谢大神！！！
