### ISSUE TITLE
支持发弹幕吗

### ISSUE THREAD

**Issue by quicksandznzn** [YunzhiYike/douyin-live#22]
请问大佬支持发弹幕吗

**Comment by YunzhiYike** [comment]
不支持
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月15日 16:52 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [YunzhiYike/douyin-live] 支持发弹幕吗 (Issue #22) |

请问大佬支持发弹幕吗
