### ISSUE TITLE
请教，如何通过google的方式去解析

### ISSUE THREAD

**Issue by JieHaoCai** [YunzhiYike/douyin-live#23]
我现在根据老师的proto文件，下载google-protobuf和protobufjs，将proto解析成js文件，接下来要如何操作呢

**Comment by JieHaoCai** [comment]
https://github.com/protocolbuffers/protobuf-javascript

**Comment by JieHaoCai** [comment]
> 用js还原吗？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Jackson ***@***.***> | | 发送日期 | 2023年08月29日 16:10 | | 收件人 | YunzhiYike/douyin-live ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [YunzhiYike/douyin-live] 请教，如何通过google的方式去解析 (Issue #23) | https://github.com/protocolbuffers/protobuf-javascript — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

你好，我现在使用google-protobuf的js版本去将proto文件解析成js文件，解析成功了，但是不知道如何将数据还原成json对象的形式

**Comment by JieHaoCai** [comment]
// 加载 .proto 文件，这里就是将解析成功的文件引入进来
var messages = require('./proto/dy_pb');
var response = messages.Response;


console.log('response', response)


var message = response.deserializeBinary(aa)
//到这里确定只能这么做了，其他方法都会报错

console.log('message', message)

**Comment by JieHaoCai** [comment]
![image](https://github.com/YunzhiYike/douyin-live/assets/92494163/53ad3abf-c101-4f41-bba0-11ee8e054f5a)

**Comment by YunzhiYike** [comment]
用gpt把Python的代码转成对应的就好了

---- 回复的原邮件 ----
| 发件人 | Jackson ***@***.***> |
| 发送日期 | 2023年08月29日 18:47 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | 云知易客 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 请教，如何通过google的方式去解析 (Issue #23) |

// 加载 .proto 文件，这里就是将解析成功的文件引入进来
var messages = require('./proto/dy_pb');
var response = messages.Response;

console.log('response', response)

var message = response.deserializeBinary(aa)
//到这里确定只能这么做了，其他方法都会报错

console.log('message', message)

**Comment by JieHaoCai** [comment]
我仔细看过py里面的方法了，但是貌似解析出来的js里面没有对应的方法

**Comment by YunzhiYike** [comment]
用GPT转

---- 回复的原邮件 ----
| 发件人 | Jackson ***@***.***> |
| 发送日期 | 2023年08月29日 18:50 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | 云知易客 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 请教，如何通过google的方式去解析 (Issue #23) |

我仔细看过py里面的方法了，但是貌似解析出来的js里面没有对应的方法

**Comment by JieHaoCai** [comment]
请问dy_pb2.py是否也是通过google去转出来的呢

**Comment by JieHaoCai** [comment]
![image](https://github.com/YunzhiYike/douyin-live/assets/92494163/c9b67c9d-5b22-4825-8bc5-f9f2d65e7b63)
