### ISSUE TITLE
忽然收不到任何消息了

### ISSUE THREAD

**Issue by bojingyu** [YunzhiYike/douyin-live#24]
大佬，我今天忽然收不到任何弹幕消息了，拉取了最新代码也是这样。房间能连上，房间里面也有人活跃，但是只有心跳在打印，请问我该如何排查呢？

**Comment by YunzhiYike** [comment]
你看看测试地址

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月29日 21:23 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [YunzhiYike/douyin-live] 忽然收不到任何消息了 (Issue #24) |

大佬，我今天忽然收不到任何弹幕消息了，拉取了最新代码也是这样。房间能连上，房间里面也有人活跃，但是只有心跳在打印，请问我该如何排查呢？

**Comment by bojingyu** [comment]
测试地址是好的呢，我拉取到本地运行就不太好，我真的什么也没改
![image](https://github.com/YunzhiYike/douyin-live/assets/13087990/10af002f-dcc6-407b-a0c9-bfac2e42c8ba)

**Comment by YunzhiYike** [comment]
没办法了，换IP 吧
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月29日 21:41 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | 云知易客 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 忽然收不到任何消息了 (Issue #24) |

测试地址是好的呢，我拉取到本地运行就不太好，我真的什么也没改

**Comment by bojingyu** [comment]
原来如此，感谢大佬指点
