### ISSUE TITLE
抖音实名认证

### ISSUE THREAD

**Issue by LHC12580** [YunzhiYike/douyin-live#26]
抖音现在需要实名认证了，大佬怎么跳过实名认证登录？

**Comment by YunzhiYike** [comment]
不行🙅🏻‍♂️

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月13日 03:08 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26) |

抖音现在需要实名认证了，大佬怎么跳过实名认证登录？

**Comment by LHC12580** [comment]
搞不了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 上午8:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26)




 不行🙅🏻‍♂️
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2023年09月13日 03:08 |
 | 收件人 | YunzhiYike/douyin-live ***@***.***&gt; |
 | 抄送人 | Subscribed ***@***.***&gt; |
 | 主题 | [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26) |
 
 抖音现在需要实名认证了，大佬怎么跳过实名认证登录？

**Comment by YunzhiYike** [comment]
违规不做

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月13日 10:04 |
| 收件人 | YunzhiYike/douyin-live ***@***.***> |
| 抄送人 | 云知易客 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26) |

搞不了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 上午8:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26)




不行🙅🏻‍♂️

---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 发送日期 | 2023年09月13日 03:08 |
| 收件人 | YunzhiYike/douyin-live ***@***.***&gt; |
| 抄送人 | Subscribed ***@***.***&gt; |
| 主题 | [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26) |

抖音现在需要实名认证了，大佬怎么跳过实名认证登录？

**Comment by LHC12580** [comment]
不是，那么多搞灰产，外挂的，&nbsp; 那么多插件模块， 腾讯每年那么多会员，超级会员，大会员，广告会员，付费会员，名正言顺的打击盗版，可是最后呢？ 这都不会违规了，比起它们所谓的官方



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 上午10:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26)




 违规不做
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2023年09月13日 10:04 |
 | 收件人 | YunzhiYike/douyin-live ***@***.***&gt; |
 | 抄送人 | 云知易客 ***@***.***&gt;,
 Comment ***@***.***&gt; |
 | 主题 | Re: [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26) |
 
 搞不了吗
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2023年9月13日(周三) 上午8:51
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26)
 
 
 
 
 不行🙅🏻‍♂️
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&amp;gt; |
 | 发送日期 | 2023年09月13日 03:08 |
 | 收件人 | YunzhiYike/douyin-live ***@***.***&amp;gt; |
 | 抄送人 | Subscribed ***@***.***&amp;gt; |
 | 主题 | [YunzhiYike/douyin-live] 抖音实名认证 (Issue #26) |
 
 抖音现在需要实名认证了，大佬怎么跳过实名认证登录？
