### ISSUE TITLE
无法获取VR直播间的信息（只有客户端和PICO端能看的直播）

### ISSUE THREAD

**Issue by tianrui233** [YunzhiYike/douyin-live#5]
![image](https://user-images.githubusercontent.com/37788769/219248847-f7956dcb-26fd-4b23-82b3-e4dffbbf007b.png)

**Comment by tianrui233** [comment]
我在安卓端抓到抖音客户端的cookie和User-Agent了，但貌似没啥用

**Comment by YunzhiYike** [comment]
> 我在安卓端抓到抖音客户端的cookie和User-Agent了，但貌似没啥用

正如你的标题所说，douyin-live是面向网页端而不是客户端；所以你连接会失败；协议都不一样
